### ISSUE TITLE
[Story] Introduce Enforce flag on Policy CRD

### ISSUE THREAD

**Issue by MostafaMegahid** [weaveworks/policy-agent#210]
#### Background: 
We are deprecating the PolicySet CR. So users need a way to define whether a policy is enforced via the admission controller or just audited for a violation. 

#### Objective: 
Introduce a new key in the PolicyCR (Enforce) to define whether the policy is enforced (e.g. blocks violating changes), or just report the violation without enforcement. 

#### Acceptance Criteria:
* Change the policy CRD to include Enforce Key. We probably need to have a new version of the policy CRD.
* Consider removing the Enabled key. It was used by the SaaS product, but not used now. 
* Enforce column in policy list, should get its data from the policy CR Enforce flag (True/False). Same for the Enforce field in the policy details page (we may have some design change to it)
* Remove the audit column and field from the list and details page. 

* Enforce Key logic
    * Enforce is true & Policy is violated, then Resource is blocked & Violation Event is reported
    * Enforce is false & Policy is violated, then Resource change is allowed & Violation Event is reported
    * If a resource has multiple policies evaluated, and any of those policies are violated and has the enforce flag equals true, then the resource change is blocked. 
    * If the agent has the failure policy as Ignore, then all violated policies are gonna report Violation Events, while not blocking any of the resources changes. 

* Violation Event Changes
    * We need to have a field in the violation event to indicate whether the violation event is enforced or not. 
    * This will need to reflect in all the violation listing and details pages across the UI.

**Comment by waleedhammam** [comment]
- Todo:
- Check the default behavior for enforce if not existed with @MostafaMegahid  
- Update the default policies / policy library
